# A sample Gemfile
source "https://rubygems.org"

# gem "rails"

gem 'sass', "3.3.14"
gem 'compass', "~>1.0.0"
gem 'sass-rails', '>= 3.2'
gem 'bootstrap-sass', '~> 3.1.1'
gem 'sass-globbing', ">= 1.1.0"